datamodule:
  _target_: "proteinfoundation.datasets.pdb_data.PDBLightningDataModule"
  data_dir: ${oc.env:DATA_PATH}/pep_train/ # Directory where the dataset is stored
  in_memory: False
  format: "cif" # format for file download
  overwrite: False # Whether to overwrite existing dataset files and reprocess the raw data
  # arguments for BaseLightningDataModule class
  batch_padding: True # whether we want a sparse PyG batch or a padded dense batch
  sampling_mode: "cluster-random" # sample randomly inside each sequence similarity cluster during training
  transforms: 
    - _target_: "proteinfoundation.datasets.transforms.GlobalRotationTransform" # Transforms to apply to dataset examples
    - _target_: "proteinfoundation.datasets.transforms.ChainBreakPerResidueTransform"
    # - _target_: "proteinfoundation.datasets.transforms.CATHLabelTransform" # activate for fold-conditional training
    #   root_dir: ${oc.env:DATA_PATH}/cathdata/ # Root directory for CATH labels
  batch_size: 4 # Batch size for dataloader
  num_workers: 16 # Number of workers for dataloader
  pin_memory: True # Pin memory for dataloader

  # dataselector:
  #   _target_: "proteinfoundation.datasets.pdb_data.PDBDataSelector"
  #   data_dir: ${oc.env:DATA_PATH}/pep_train/ # Directory where the dataset is stored
  #   fraction: 0.95 # Fraction of dataset to use
  #   molecule_type: "protein" # Type of molecule for which to select
  #   experiment_types: ["diffraction", "EM"] # other options are "NMR" and "other"
  #   min_length: 8 # Exclude peptides of length 50
  #   max_length: 512 # Exclude polypeptides greater than length 500
  #   oligomeric_min: null 
  #   oligomeric_max: null 
  #   best_resolution: 0.0  # Include only proteins with resolution >= 0.0
  #   worst_resolution: 5.0 # Include only proteins with resolution <= 5.0
  #   has_ligands: [] # Include only proteins containing the ligand `ZN`
  #   remove_ligands: [] # Exclude specific ligands from any available protein-ligand complexes
  #   remove_non_standard_residues: True # Include only proteins containing standard amino acid residues
  #   remove_pdb_unavailable: True # Include only proteins that are available to download
  #   exclude_ids: []   # IDs can be excluded here like ["9b57", "1crr"]

  datasplitter:
    _target_: "proteinfoundation.datasets.pdb_data.PDBDataSplitter"
    data_dir: ${oc.env:DATA_PATH}/pep_train/ # Directory where the dataset is stored
    train_val_test: [0.98, 0.019, 0.001] # Cross-validation ratios to use for train, val, and test splits
    split_type: "sequence_similarity" # Split sequences by sequence similarity clustering, other option is "random"
    split_sequence_similarity: 0.75 # Clustering at 50% sequence similarity (argument is ignored if split_type!="sequence_similarity")
    overwrite_sequence_clusters: False # Previous clusterings at same sequence similarity are reused and not overwritten (argument is ignored if split_type!="sequence_similarity")

